# Generated by Django 3.1.11 on 2021-10-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='class title', max_length=50)),
                ('create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='FormMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FromMaster',
                'verbose_name_plural': 'FromMasters',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': "LGA's",
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=30)),
                ('create_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='studentavar.png', null=True, upload_to='students')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('previous_school', models.CharField(blank=True, help_text='previous school', max_length=50, null=True)),
                ('physical_disability', models.CharField(blank=True, max_length=50, null=True)),
                ('allergy', models.CharField(blank=True, max_length=50, null=True)),
                ('admitted', models.BooleanField(blank=True, null=True)),
                ('admitted_date', models.DateField(blank=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('pp', models.BooleanField(blank=True, default=False)),
                ('nus1', models.BooleanField(blank=True, default=False)),
                ('nus2', models.BooleanField(blank=True, default=False)),
                ('nus3', models.BooleanField(blank=True, default=False)),
                ('primary1', models.BooleanField(blank=True, default=False)),
                ('primary2', models.BooleanField(blank=True, default=False)),
                ('primary3', models.BooleanField(blank=True, default=False)),
                ('primary4', models.BooleanField(blank=True, default=False)),
                ('primary5', models.BooleanField(blank=True, default=False)),
                ('jss1', models.BooleanField(blank=True, default=False)),
                ('jss2', models.BooleanField(blank=True, default=False)),
                ('jss3', models.BooleanField(blank=True, default=False)),
                ('ss1', models.BooleanField(blank=True, default=False)),
                ('ss2', models.BooleanField(blank=True, default=False)),
                ('ss3', models.BooleanField(blank=True, default=False)),
                ('c_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='Students.class')),
                ('lga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.lga')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.state')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('test1', models.IntegerField()),
                ('test2', models.IntegerField()),
                ('assignment1', models.IntegerField()),
                ('assignment2', models.IntegerField()),
                ('Exam', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('Average', models.FloatField()),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tribe',
                'verbose_name_plural': 'Tribes',
            },
        ),
        migrations.CreateModel(
            name='StudentToSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.subject')),
            ],
            options={
                'verbose_name': 'StudentToSubjects',
                'verbose_name_plural': 'StudentToSubjects',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.tribe'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.state'),
        ),
    ]
