# Generated by Django 3.1.11 on 2021-10-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmaster',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacher'),
        ),
        migrations.AddField(
            model_name='formmaster',
            name='f_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.session'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='class_subjects', through='Students.StudentToSubjects', to='Students.Subject'),
        ),
    ]
