# Generated by Django 3.1.11 on 2021-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20211019_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Average',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Exam',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assignment1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assignment2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='test1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='test2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_score',
            field=models.IntegerField(blank=True),
        ),
    ]
