# Generated by Django 3.1.11 on 2021-10-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_auto_20211023_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Average',
            field=models.FloatField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Exam',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assignment1',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assignment2',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='test1',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='test2',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_score',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
