# Generated by Django 3.1.11 on 2021-10-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_auto_20211025_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='total_score',
            new_name='total',
        ),
    ]
