# Generated by Django 3.1.11 on 2021-10-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_auto_20211026_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Average',
        ),
    ]
