# Generated by Django 3.1.11 on 2021-10-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_auto_20211026_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Exam',
            new_name='Exam_term1',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='assignment1',
            new_name='Exam_term2',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='assignment2',
            new_name='Exam_term3',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='test1',
            new_name='assignment1_term1',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='test2',
            new_name='assignment1_term2',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='total',
            new_name='assignment1_term3',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='grade',
            new_name='grade_term1',
        ),
        migrations.AddField(
            model_name='subject',
            name='assignment2_term1',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='assignment2_term2',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='assignment2_term3',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_term2',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_term3',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='test1_term1',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test1_term2',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test1_term3',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test2_term1',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test2_term2',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test2_term3',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_term1',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_term2',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_term3',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
    ]
