# Generated by Django 3.1.11 on 2021-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_auto_20211026_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='real_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
