# Generated by Django 3.1.11 on 2021-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_auto_20211030_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
