# Generated by Django 3.1.11 on 2021-11-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0014_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='average',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
