# Generated by Django 3.1.11 on 2021-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0015_auto_20211111_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='average',
            field=models.FloatField(null=True),
        ),
    ]
