# Generated by Django 3.1.11 on 2021-11-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0019_result_totall_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='attendace',
            new_name='attendance',
        ),
        migrations.AddField(
            model_name='rating',
            name='class_teacher_remark',
            field=models.CharField(blank=True, default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='principal_remark',
            field=models.CharField(blank=True, default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='term',
            field=models.CharField(choices=[(1, 'term1'), (2, 'term2'), (3, 'term3')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='r_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class_rating', to='Students.class'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rating', to='Students.student'),
        ),
    ]
