# Generated by Django 3.1.11 on 2021-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0020_auto_20211113_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='physical_participation',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='ralationship_with_others',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=10),
        ),
    ]
