# Generated by Django 3.1.11 on 2021-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0021_auto_20211114_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='students'),
        ),
    ]
