# Generated by Django 3.2.12 on 2022-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0023_auto_20211129_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('science', 'science'), ('social', 'social'), ('all', 'all')], default='all', max_length=50),
        ),
    ]
