# Generated by Django 3.2.12 on 2022-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0025_auto_20220627_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='secondary',
            field=models.BooleanField(default=False),
        ),
    ]
