# Generated by Django 3.2.12 on 2024-01-12 19:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_remove_teacher_photo'),
        ('Students', '0026_class_secondary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('lesson_date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('objectives', ckeditor.fields.RichTextField()),
                ('previous_knowledge', ckeditor.fields.RichTextField()),
                ('instructional_materials', models.TextField()),
                ('introduction', ckeditor.fields.RichTextField()),
                ('lesson_content', ckeditor.fields.RichTextField()),
                ('teaching_methodology', ckeditor.fields.RichTextField()),
                ('assessment', ckeditor.fields.RichTextField()),
                ('conclusion', ckeditor.fields.RichTextField()),
                ('homework_assignment', ckeditor.fields.RichTextField()),
                ('reflection', ckeditor.fields.RichTextField()),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Teachers.teacher')),
            ],
        ),
    ]
