# Generated by Django 3.2.12 on 2024-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0027_lessonnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonnote',
            name='reflection',
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='teaching_methodology',
            field=models.TextField(),
        ),
    ]
