# Generated by Django 3.2.12 on 2024-01-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]