# Generated by Django 3.1.11 on 2021-10-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211019_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(default='teacheravatar.jpg', upload_to='teachers')),
                ('date_of_birth', models.DateField()),
                ('designation', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=5)),
                ('edu_level', models.CharField(blank=True, choices=[('Btech', 'Bachelor of technology'), ('Bsc', 'Bachelor of science'), ('Phd', 'Phd'), ('Dr', 'Doctor')], max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('other_qual', models.CharField(help_text='separate with comma', max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('joining_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['joining_date', 'firstname'],
            },
        ),
    ]
