# Generated by Django 3.1.11 on 2021-10-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname',
            new_name='middlename',
        ),
    ]
