# Generated by Django 3.1.11 on 2021-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_auto_20211019_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='teacheravatar.jpg', upload_to='teachers'),
        ),
    ]
