# Generated by Django 3.1.11 on 2021-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_auto_20211102_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='teachers'),
        ),
    ]
